### ISSUE TITLE
[BUG] isConsentApproved() condition fails when form sent via tslib

### ISSUE THREAD

**Issue by zabinetta** [eliashaeussler/typo3-form-consent#98] opened 2023-03-01 12:39 UTC
### TYPO3 version

11.5.24

### PHP version

7.4

### Extension version

064

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

-

### Current behavior

Dear Elias, 
sorry for bothering you with this rather odd problem, I hope I can explain it good enough..
I have a yaml-form, it is for signing in for a seminar.
That's why I call the form inside a plugin-template, via f:cObject.

When I send the form via plugin (simple configuration, the receiverMail placed in the basic form-finisher), I get the approval-mail along with the receiverMail and can also approve the consent. So far so good. 

Now I move the receiverMail to the Condition variant, so when I send the form via plugin (the receiverMail placed in the variant with isConsentApproved() condition), I get the approval-mail, I click the link, but **I don't get the receiverMail.**

The funny thing is: when I create a content-element, using the same form (the receiverMail placed in the variant with isConsentApproved() condition), it works perfect: I send the form, get the consent-mail, click the link , and there is the receiverMail but no prefill...

So in order to get the approval working, is the form needed as a content-element?

```
lib.lganmeldeform_mask = COA_INT
lib.lganmeldeform_mask {
   #formular aufrufen
  20 = FLUIDTEMPLATE
  20 {
    template = TEXT
    template { 
//the seminar param must be given with the form in order to stay in the right plugin view
      value = <formvh:render persistenceIdentifier="fileadmin/form_definitions/lehrgangsanmeldung.form.yaml" overrideConfiguration="{renderingOptions:{additionalParams:{tx_myext_seminar:{action:'show',controller:'seminarDetail',seminarDetail:detaillga}}},renderables: {0: {renderables: {0: {defaultValue: veranstaltungsinfo},1: {defaultValue: place},2: {defaultValue: termin},3: {defaultValue: price},4:{defaultValue:remarks}}}}}" />
    }
        extbase {
        pluginName = Formframework
        controllerExtensionName = Form
        controllerName = FormFrontend
        controllerActionName = perform
    }
  variables {
    veranstaltungsinfo = TEXT
    veranstaltungsinfo.field = veranstaltungsinfo
     detaillga = TEXT
    detaillga.data = register:detaillga
    termin = TEXT
    termin.field = termin
    price = TEXT
    price.field = price
    price.noTrimWrap = || €|
    place = TEXT
    place.field = ort
    remarks = TEXT
    remarks.field = remarks
   }
    }
}
```

### Expected behavior

I would like if the isConsentApproved() condition would working via typoscript, too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment] 2023-03-01 13:24
Hi @zabinetta, can you post your `finishers` and `variants` properties from you form.yaml file?

**Comment by zabinetta** [comment] 2023-03-01 13:48
`
renderingOptions:
  addQueryString: true
  submitButtonLabel: Absenden
  fieldState:
    lgatitel:
      type: Hidden
      identifier: lgatitel
      label: Lehrgang
      renderingOptions:
        deleted: 0
        listView: 1
...

type: Form
identifier: lehrgangsanmeldung3
label: Lehrgangsanmeldung3
prototypeName: standard
variants:
  -
    identifier: variant-consent-approved
    condition: 'isConsentApproved()'
    finishers:
      -
        options:
          subject: 'Lehrgangsanmeldung {lgatitel}'
          recipients:
            sabine@email.de: 'Sabine'
          senderAddress: '{ap_email}'
          senderName: '{ap_titel} {ap_vorname} {ap_name}'
          addHtmlPart: true
          attachUploads: false
          translation:
            language: Default
          useFluidEmail: true
          title: 'Lehrgangsanmeldung {lgatitel}'
          templateName: Anmeldung
          templateRootPaths:
            200: 'EXT:sitepackage/Resources/Private/Templates/txForm/lgamail/'
          layoutRootPaths:
            200: 'EXT:sitepackage/Resources/Private/Layouts/txForm/lgamail/'
        identifier: EmailToReceiver
finishers:
  -
    options:
      subject: ''
      recipientAddress: '{ap_email}'
      recipientName: '{ap_name}'
      senderAddress: lga@slvtemp.de
      senderName: 'automatische mail'
      approvalPeriod: '86400'
      showDismissLink: true
      confirmationPid: '10181'
      storagePid: '10181'
    identifier: Consent
  -
    options:
      message: 'Schauen Sie jetzt in Ihr E-Mail-Programm und bestätigen Sie Ihre Anmeldung. Erst dann können wir diese weiter bearbeiten.'
      contentElementUid: ''
    identifier: Confirmation
  -
    identifier: LogFormData
 [...]

**Comment by eliashaeussler** [comment] 2023-03-01 16:46
@zabinetta Thanks! I'll try to reproduce the problem and will come back to you then.

**Comment by eliashaeussler** [comment] 2023-04-12 14:16
@zabinetta Sorry for the late reply. I'm afraid this scenario is not possible with the current implementation, because it requires rendering within a content element:

https://github.com/eliashaeussler/typo3-form-consent/blob/1776d027f51158d71d75cc79682d5933ea1cedba/Classes/Event/Listener/InvokeFinishersListener.php#L90-L96

I may have a look at this when upgrading to TYPO3 v12, but it's definitely more a feature than a bug, because the whole re-rendering concept must be rewritten. I'm sorry, but I feel like the only solution at the moment is to use the content element (= plugin) rendering approach.

**Comment by eliashaeussler** [comment] 2023-11-17 21:09
I'm closing this issue, because further implementation is not planned.

**Closed by eliashaeussler** 2023-11-17 21:09 UTC
Labels: bug
